### ISSUE TITLE
Script #4 doesn't run off repo

### ISSUE THREAD

**Issue by BronwynMacDonald** [BronwynMacDonald/Scanner-Data-Processing#2]
To make this run, the Algorithm code needs to be added to the repo then the lines of code can be updated to reference this. Also, currently this script writes files directly into the data prep repo for the scanner so they don't have to be moved. we will need to set something up for transferring those files.

**Comment by SOLV-Code** [comment]
OK.  will take a look re: algorithm fn, but for the input/output setup we might need a quick call early Jan to map out the details?
